{
    'name': 'Mass Battle',
    'version': '1.0',
    'category': 'JdR',
    'complexity': 'easy',
    'description': """Mass Battle""",
    'depends': [
        'mail',
    ],
    'data': [
        'security/ir.access.csv',
        'wizard/battle_solver_views.xml',
        'wizard/battle_unit_sheet_wizard_views.xml',
        'report/battle_unit_sheet_templates.xml',
        'report/battle_location_sheet_templates.xml',
        'report/battle_rules_reference_templates.xml',
        'views/battle_result_views.xml',
        'views/battle_round_views.xml',
        'views/battle_faction_views.xml',
        'views/battle_leader_views.xml',
        'views/battle_outcome_views.xml',
        'views/battle_location_views.xml',
        'views/battle_trait_views.xml',
        'views/battle_unit_template_views.xml',
        'views/battle_unit_views.xml',
        'views/battle_dashboard_views.xml',
        'views/battle_menus.xml',
        'data/battle_trait_data.xml',
        'data/battle_faction_data.xml',
        'data/battle_location_data.xml',
        'data/battle_leader_data.xml',
        'data/battle_outcome_data.xml',
        'data/battle.unit.template.csv',
        'data/battle.unit.csv',
        'data/battle_round_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'odoo_battle/static/src/**/*',
        ],
    },
    'author': "Thibault Delavallee",
    'license': 'LGPL-3',
}
